### PR TITLE
Add Shakespeare ipsum

### PR DESCRIPTION
**Pull request by Steven24K**
Hi @Sena , 

I found your Lorum Ipsum generator on the web. Intersting concept, I have seen many different kind of ipsums on the web (bacon psum is really nice) and I use them on testing environments for dummy content. This makes working with dummy text so much more fun. 

I am a big fan of theatre and Shakespeare so I thought lets combine it and put William Shakespeare greatest and most famous monoloques in the lorum ipsum generator.

### CODE REVIEW

**Comment by ramon-src** [comment]
Hi @Steven24K thanks for sharing your Ipsum! We are really happy that this tool is useful to you, you are the first one to send us a custom Ipsum! 

I've notice that in your file, the key is copied by arnold. Please change that to the shakespeare file name (without .md) then I can approve it!

**Comment by Steven24K** [comment]
Yes now I see it as well. I copied the file from Arnold's ipsum.

I also forgot to change the colors, so I will also pick some custom colors.

**Comment by Steven24K** [comment]
@ramon-src  I changed the key and colors. The key only being used to uniquely identify an ipsum right?

**Comment by Steven24K** [comment]
@Sena @ramon-src have you got time to review the changes I made and accept my pull request.

I am hope it can go through, cause I am planning to share the Shakespeare ipsum on social media.

So more people will submit there own ipsum in the future.

**Pull request merged**
